# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

saBivariateBD <- function(J, alphaR, alphaT, beta, Nmin, Nmax, equal_n, dbivar_00_list, dbivar_01_list, dbivar_10_list, dbivar_11_min_list, dbivar_11_max_list, summary) {
    .Call('_singlearm_saBivariateBD', PACKAGE = 'singlearm', J, alphaR, alphaT, beta, Nmin, Nmax, equal_n, dbivar_00_list, dbivar_01_list, dbivar_10_list, dbivar_11_min_list, dbivar_11_max_list, summary)
}

saBivariateCP <- function(J, alphaL, alphaG, beta, Nmin, Nmax, equal_n, dbivar_00_list, dbivar_01_list, dbivar_10_list, dbivar_11_list, dbivar_max1_list, dbivar_max2_list, summary) {
    .Call('_singlearm_saBivariateCP', PACKAGE = 'singlearm', J, alphaL, alphaG, beta, Nmin, Nmax, equal_n, dbivar_00_list, dbivar_01_list, dbivar_10_list, dbivar_11_list, dbivar_max1_list, dbivar_max2_list, summary)
}

saGS <- function(J, pi0, pi1, alpha, beta, Nmin, Nmax, futility, efficacy, equal_n, ensign, summary) {
    .Call('_singlearm_saGS', PACKAGE = 'singlearm', J, pi0, pi1, alpha, beta, Nmin, Nmax, futility, efficacy, equal_n, ensign, summary)
}

saVariable <- function(J, pi0, pi1, alpha, beta, v, Nmin, Nmax, equal_n) {
    .Call('_singlearm_saVariable', PACKAGE = 'singlearm', J, pi0, pi1, alpha, beta, v, Nmin, Nmax, equal_n)
}

